### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by PieceTheLord** [shodon2007/networth-client#4]
![image_2024-03-18_144007356](https://github.com/shodon2007/NetWorth/assets/133156395/44015c0e-cf1a-4738-bf81-25beb78dae9c)

![Uploading Screenshot (40).png…]()

**Comment by PieceTheLord** [comment]
![Uploading Screenshot (40).png…]()

**Comment by shodon2007** [comment]
hellow

**Comment by PieceTheLord** [comment]
![Uploading image_2024-03-18_144141451.png…]()
